# Generated by Django 5.2.11 on 2026-02-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_full_description_discount_sale'),
        ('users', '0002_shipping_and_order_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_wishlist',
                'indexes': [models.Index(fields=['user'], name='idx_wishlist_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='users_wishlist_user_product_unique')],
            },
        ),
    ]
