from django.urls import path

from . import api_views

urlpatterns = [
    path("auth/login/", api_views.api_login),
    path("auth/register/", api_views.api_register),
    path("auth/me/", api_views.api_me),
    path("auth/logout/", api_views.api_logout),
    path("stores/", api_views.api_stores),
    path("stores/<int:store_id>/", api_views.api_store_detail),
    path("stores/<int:store_id>/products/", api_views.api_store_products),
    path("sellers/", api_views.api_sellers),
    path("sellers/<int:seller_id>/", api_views.api_seller_detail),
    path("sellers/<int:seller_id>/stores/", api_views.api_seller_stores),
    path("products/", api_views.api_products),
    path("products/<int:pk>/", api_views.api_product_detail),
    path("products/<int:pk>/related/", api_views.api_product_related),
    path("cart/", api_views.api_cart_list),
    path("cart/add/", api_views.api_cart_add),
    path("cart/update/", api_views.api_cart_update),
    path("cart/remove/<int:product_id>/", api_views.api_cart_remove),
    path("cart/clear/", api_views.api_cart_clear),
    path("users/me/", api_views.api_user_update),
    path("users/me/change-password/", api_views.api_change_password),
    path("users/me/addresses/", api_views.api_address_list),
    path("users/me/addresses/create/", api_views.api_address_create),
    path("users/me/addresses/<int:addr_id>/", api_views.api_address_update),
    path("users/me/addresses/<int:addr_id>/delete/", api_views.api_address_delete),
    path("orders/", api_views.api_orders),
    path("orders/<int:order_id>/", api_views.api_order_detail),
    path("orders/<int:order_id>/cancel/", api_views.api_order_cancel),
    path("wishlist/", api_views.api_wishlist_list),
    path("wishlist/<int:product_id>/add/", api_views.api_wishlist_add),
    path("wishlist/<int:product_id>/remove/", api_views.api_wishlist_remove),
    path("dashboard/", api_views.api_dashboard),
    path("dashboard/tree/", api_views.api_tree_data),
    path("dashboard/bonus-events/", api_views.api_bonus_events),
]
