# Generated by Django 5.2.11 on 2026-02-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingCounter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pairing_counter', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('left_count', models.PositiveIntegerField(default=0)),
                ('right_count', models.PositiveIntegerField(default=0)),
                ('released_pairs', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pairing_counters',
            },
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('depth', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.treenode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_node', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tree_nodes',
                'indexes': [models.Index(fields=['parent'], name='idx_tree_parent'), models.Index(fields=['depth'], name='idx_tree_depth')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'lane'), name='tree_unique_parent_lane')],
            },
        ),
    ]
