# Generated by Django 5.2.11 on 2026-02-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('DIRECT', 'Direct'), ('HIERARCHY', 'Hierarchy')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lane', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('depth', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_events', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bonus_events',
                'indexes': [models.Index(fields=['user'], name='idx_bonus_user'), models.Index(fields=['order'], name='idx_bonus_order'), models.Index(fields=['status'], name='idx_bonus_status')],
            },
        ),
    ]
