# Generated by Django 5.2.11 on 2026-02-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_full_description_discount_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Path under MEDIA_ROOT, e.g. products/Electronics.jpg', max_length=255),
        ),
    ]
